export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_LOADING = 'GET_PHOTOS_LOADING';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';

export const LOADING_REGISTER = 'LOADING_REGISTER';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';

export const LOADING_LOGIN = 'LOADING_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ERROR_LOGOUT = 'ERROR_LOGOUT';